#!/bin/sh

# Disable text console
echo 0 > /sys/devices/virtual/vtconsole/vtcon1/bind

# Reset clock frequency to the default one
echo 360000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed

if [ -x /usr/local/home/.autostart ] ; then
	exec /usr/local/home/.autostart
else
	exec /usr/bin/gmenu2x
fi
